version: "2"
services:

  # Edge framework services --------------------------------

  edge-server:
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: server/Dockerfile

  device-service:
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: device/Dockerfile

  mqtt-service:
    network_mode: "host"
    privileged: true
    ports:
      - 1883:1883
      - 9001:9001
    image: arm32v6/eclipse-mosquitto

  # Custom services -----------------------------------------
